// Countries with their legal system context for contract analysis
export const COUNTRIES = [
  { code: "US", name: "United States", flag: "\ud83c\uddfa\ud83c\uddf8", legalSystem: "Common Law (Federal + State)" },
  { code: "GB", name: "United Kingdom", flag: "\ud83c\uddec\ud83c\udde7", legalSystem: "Common Law" },
  { code: "CA", name: "Canada", flag: "\ud83c\udde8\ud83c\udde6", legalSystem: "Common Law (Federal + Provincial)" },
  { code: "AU", name: "Australia", flag: "\ud83c\udde6\ud83c\uddfa", legalSystem: "Common Law (Federal + State)" },
  { code: "IN", name: "India", flag: "\ud83c\uddee\ud83c\uddf3", legalSystem: "Common Law (Indian Contract Act)" },
  { code: "DE", name: "Germany", flag: "\ud83c\udde9\ud83c\uddea", legalSystem: "Civil Law (BGB)" },
  { code: "FR", name: "France", flag: "\ud83c\uddeb\ud83c\uddf7", legalSystem: "Civil Law (Code Civil)" },
  { code: "NL", name: "Netherlands", flag: "\ud83c\uddf3\ud83c\uddf1", legalSystem: "Civil Law" },
  { code: "SG", name: "Singapore", flag: "\ud83c\uddf8\ud83c\uddec", legalSystem: "Common Law" },
  { code: "AE", name: "United Arab Emirates", flag: "\ud83c\udde6\ud83c\uddea", legalSystem: "Civil Law (UAE Civil Code)" },
  { code: "SA", name: "Saudi Arabia", flag: "\ud83c\uddf8\ud83c\udde6", legalSystem: "Islamic Law (Sharia)" },
  { code: "JP", name: "Japan", flag: "\ud83c\uddef\ud83c\uddf5", legalSystem: "Civil Law" },
  { code: "KR", name: "South Korea", flag: "\ud83c\uddf0\ud83c\uddf7", legalSystem: "Civil Law" },
  { code: "BR", name: "Brazil", flag: "\ud83c\udde7\ud83c\uddf7", legalSystem: "Civil Law" },
  { code: "MX", name: "Mexico", flag: "\ud83c\uddf2\ud83c\uddfd", legalSystem: "Civil Law" },
  { code: "ZA", name: "South Africa", flag: "\ud83c\uddff\ud83c\udde6", legalSystem: "Mixed (Roman-Dutch + Common Law)" },
  { code: "NG", name: "Nigeria", flag: "\ud83c\uddf3\ud83c\uddec", legalSystem: "Common Law" },
  { code: "KE", name: "Kenya", flag: "\ud83c\uddf0\ud83c\uddea", legalSystem: "Common Law" },
  { code: "PH", name: "Philippines", flag: "\ud83c\uddf5\ud83c\udded", legalSystem: "Mixed (Civil + Common Law)" },
  { code: "ID", name: "Indonesia", flag: "\ud83c\uddee\ud83c\udde9", legalSystem: "Civil Law" },
  { code: "PK", name: "Pakistan", flag: "\ud83c\uddf5\ud83c\uddf0", legalSystem: "Common Law (Pakistan Contract Act)" },
  { code: "BD", name: "Bangladesh", flag: "\ud83c\udde7\ud83c\udde9", legalSystem: "Common Law" },
  { code: "NZ", name: "New Zealand", flag: "\ud83c\uddf3\ud83c\uddff", legalSystem: "Common Law" },
  { code: "IE", name: "Ireland", flag: "\ud83c\uddee\ud83c\uddea", legalSystem: "Common Law" },
  { code: "SE", name: "Sweden", flag: "\ud83c\uddf8\ud83c\uddea", legalSystem: "Civil Law" },
  { code: "CH", name: "Switzerland", flag: "\ud83c\udde8\ud83c\udded", legalSystem: "Civil Law" },
  { code: "IT", name: "Italy", flag: "\ud83c\uddee\ud83c\uddf9", legalSystem: "Civil Law" },
  { code: "ES", name: "Spain", flag: "\ud83c\uddea\ud83c\uddf8", legalSystem: "Civil Law" },
  { code: "PT", name: "Portugal", flag: "\ud83c\uddf5\ud83c\uddf9", legalSystem: "Civil Law" },
  { code: "PL", name: "Poland", flag: "\ud83c\uddf5\ud83c\uddf1", legalSystem: "Civil Law" },
  { code: "IL", name: "Israel", flag: "\ud83c\uddee\ud83c\uddf1", legalSystem: "Mixed (Common + Civil Law)" },
  { code: "EG", name: "Egypt", flag: "\ud83c\uddea\ud83c\uddec", legalSystem: "Civil Law (mixed with Islamic Law)" },
  { code: "MY", name: "Malaysia", flag: "\ud83c\uddf2\ud83c\uddfe", legalSystem: "Common Law" },
  { code: "TH", name: "Thailand", flag: "\ud83c\uddf9\ud83c\udded", legalSystem: "Civil Law" },
  { code: "VN", name: "Vietnam", flag: "\ud83c\uddfb\ud83c\uddf3", legalSystem: "Civil Law" },
  { code: "OTHER", name: "Other / Not Listed", flag: "\ud83c\udf0d", legalSystem: "General" },
];

export function getCountryByCode(code) {
  return COUNTRIES.find((c) => c.code === code) || COUNTRIES[COUNTRIES.length - 1];
}
